# Numpy Assignment

* reshape(-1,1)
* copy()
* view()
* broadcasting

In [12]:
import numpy as np
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [2]:
np.random.random((3,4))
np.linspace(-10,5,9,dtype=int)

array([-10,  -9,  -7,  -5,  -3,  -1,   1,   3,   5])

In [3]:
np.random.random((3,4))

array([[0.98643875, 0.02811579, 0.83474436, 0.53369164],
       [0.12992796, 0.84654988, 0.0413379 , 0.94890949],
       [0.56708712, 0.752803  , 0.5185663 , 0.28589049]])

In [8]:
a1=[1,2,3,4,5,6,7,8]
for i in a1:
  print(i)

1
2
3
4
5
6
7
8


**reshape(-1,1)**

In [9]:
a2=np.array([1,2,3,4,5,6,7,8])
a2.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

**copy()**

In [10]:
x = np.array([1, 2, 3])
y = x
z = np.copy(x)

In [12]:
x[0] = 10
x[0] == y[0]

True

In [14]:
x[0] == z[0]
print("x :: ",x)
print("y :: ",y)
print("z :: ",z)

x ::  [10  2  3]
y ::  [10  2  3]
z ::  [1 2 3]


**view()**

In [13]:
v=np.arange(12).reshape(3,4)
print(v)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
v1=v.view()
print(v1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
v1*=2
print(v1)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [16]:
print(v)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


**Broadcasting**

In [15]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [5]:
a3 = np.arange(6).reshape(2,3)
b3 = np.arange(6,12).reshape(2,3)

print(a3)
print(b3)

print(a3+b3)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


**set any value of array true or false**

In [9]:
a3[:]==3

array([[False, False, False],
       [ True, False, False]])

# dot product

In [22]:
n1 = np.arange(8).reshape(2,4)
n2 = np.arange(8).reshape(4,2)
print("n1 :: ",n1)
print("\nn2 :: ",n2)

n1 ::  [[0 1 2 3]
 [4 5 6 7]]

n2 ::  [[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [25]:
n3=np.dot(n1,n2)
print("dot product of n1 and n2 usinh method 1 :: ",n3)

dot product of n1 and n2 usinh method 1 ::  [[28 34]
 [76 98]]


In [26]:
n3=n1.dot(n2)
print("dot product of n1 and n2 usinh method 2 :: ",n3)

dot product of n1 and n2 usinh method 2 ::  [[28 34]
 [76 98]]


In [27]:
n3=n1@n2
print("dot product of n1 and n2 usinh method 3 :: ",n3)

dot product of n1 and n2 usinh method 3 ::  [[28 34]
 [76 98]]


In [28]:
n3=np.matmul(n1,n2)
print("dot product of n1 and n2 usinh method 4 :: ",n3)

dot product of n1 and n2 usinh method 4 ::  [[28 34]
 [76 98]]
