# **Numpy Lab-1 Task**

**numpy array**

**1D array**

In [28]:
import numpy as np

a=np.array([1,2,3])
print(a)

[1 2 3]


**2D and 3D array**

In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Shape**

Shape used for array dimensions

In [ ]:
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(2, 2, 2)


# **ndim**
ndim used for Number of array dimensions

In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
c.ndim

3

# **arange() and reshape()**

arange used for create array

reshape used for reshape the array dimensions

In [ ]:
x=np.arange(3,7)
print(x)
y=np.arange(6).reshape((3,2))
print(y)
print(x.shape)
print(y.shape)

[3 4 5 6]
[[0 1]
 [2 3]
 [4 5]]
(4,)
(3, 2)


In [ ]:
z=np.arange(24).reshape(2,3,4)
print(z)
print(z.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [ ]:
ar=np.arange(12).reshape(3,4)
print(ar)
print(ar.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [ ]:
x.ndim

1

In [ ]:
y.ndim

2

In [ ]:
z.ndim

3

In [ ]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
np.arange(48).reshape(2,2,3,4)

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]],


       [[[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]],

        [[36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]]])

# **Indexing and slicing**

In [ ]:
a1=np.arange(10)
print("a1 : ",a1)
print()
a2=np.arange(12).reshape(3,4)
print("a2 : ",a2)
print()
a3=np.arange(8).reshape(2,2,2)
print("a3 : ",a3)

a1 :  [0 1 2 3 4 5 6 7 8 9]

a2 :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a3 :  [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
print("a[5]: ",a1[5])
print("a[1:]: ",a1[1:])
print("a[1:5]: ",a1[1:5])
print("a[3:8]: ",a1[3:8])
print("a[3:8:2]: ",a1[3:8:2])
print("a[-10:-5:2]: ",a1[-10:-5:2])
print("a[-1:-8:2]: ",a1[-1:-8:2])
print("a[-1:-8:-2]: ",a1[-1:-8:-2])

a[5]:  5
a[1:]:  [1 2 3 4 5 6 7 8 9]
a[1:5]:  [1 2 3 4]
a[3:8]:  [3 4 5 6 7]
a[3:8:2]:  [3 5 7]
a[-10:-5:2]:  [0 2 4]
a[-1:-8:2]:  []
a[-1:-8:-2]:  [9 7 5 3]


In [ ]:
print("a2[1:,1:]:", a2[1:,1:])
print("a2[1:]:", a2[1:])
print("a2[1:,0::3]: ",a2[1:,0::3])

a2[1:,1:]: [[ 5  6  7]
 [ 9 10 11]]
a2[1:]: [[ 4  5  6  7]
 [ 8  9 10 11]]
a2[1:,0::3]:  [[ 4  7]
 [ 8 11]]


In [ ]:
print(a3[1,1:])
print(a3[1,1])
print(a3[0,1,1])

[[6 7]]
[6 7]
3


In [ ]:
a4=np.arange(27).reshape(3,3,3)
print(a4)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
print(a4[::2,0,::2])

[[ 0  2]
 [18 20]]


# **random.randit()**

random.randit used for create array which element is random no.

In [ ]:
q=np.random.randint(1,100,24).reshape(6,4)
print(q)

[[33 71 79 95]
 [53 31 21 94]
 [96 63 95 34]
 [71 47 93 53]
 [84 73  4 71]
 [36 29 39  6]]


In [ ]:
print("q[q>50]: ",q[q>50])
print("even no.: ",q[q%2==0])

q[q>50]:  [71 79 95 53 94 96 63 95 71 93 53 84 73 71]
even no.:  [94 96 34 84  4 36  6]


In [ ]:
m=np.isin(q,[31,78])
print(m)

[[False False False False]
 [False  True False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
